const myName = 'Olga';
console.log(myName);
const mySurname = 'Shpylova';
console.log(mySurname);
let myFavoriteDrink = 'Coffee';
console.log(myFavoriteDrink);
let myFavoriteAnimal = 'Cat';
console.log(myFavoriteAnimal);
let myFavoriteProgrammingLanguage = 'JavaScript';
console.log(myFavoriteProgrammingLanguage);